// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
   

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBl_wX34A3zQlkx4wqY_cIqGMFIdMSkrug',
    appId: '1:218986886946:web:b23e35e89763ba29fbd77b',
    messagingSenderId: '218986886946',
    projectId: 'task-manager-app-95c62',
    authDomain: 'task-manager-app-95c62.firebaseapp.com',
    storageBucket: 'task-manager-app-95c62.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUASZj4ZPGlQ8Nv17pWX0tGzYXqRqjs4k',
    appId: '1:218986886946:android:946bcdbae3c31510fbd77b',
    messagingSenderId: '218986886946',
    projectId: 'task-manager-app-95c62',
    storageBucket: 'task-manager-app-95c62.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTM3vB-WetG_YgbOlCwc-15-lP86j1LwY',
    appId: '1:218986886946:ios:4e27a1c58cba86dbfbd77b',
    messagingSenderId: '218986886946',
    projectId: 'task-manager-app-95c62',
    storageBucket: 'task-manager-app-95c62.firebasestorage.app',
    iosBundleId: 'com.example.flutterUiClass',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTM3vB-WetG_YgbOlCwc-15-lP86j1LwY',
    appId: '1:218986886946:ios:4e27a1c58cba86dbfbd77b',
    messagingSenderId: '218986886946',
    projectId: 'task-manager-app-95c62',
    storageBucket: 'task-manager-app-95c62.firebasestorage.app',
    iosBundleId: 'com.example.flutterUiClass',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBl_wX34A3zQlkx4wqY_cIqGMFIdMSkrug',
    appId: '1:218986886946:web:b8e9a466d386598afbd77b',
    messagingSenderId: '218986886946',
    projectId: 'task-manager-app-95c62',
    authDomain: 'task-manager-app-95c62.firebaseapp.com',
    storageBucket: 'task-manager-app-95c62.firebasestorage.app',
  );
}
